name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2 # ソースコードをチェックアウト
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_11.4.app/Contents/Developer'
      - name: Install XcodeGen
        run: brew install xcodegen
      - name: Generate xcodeproj
        run: xcodegen
      - name: Build
        run: xcodebuild -sdk iphonesimulator -configuration Debug build
